// ─── src/data.js — Radical Intelligence Platform constants ──────────────────

export const DATE_RANGES = [
  { id:"7d",  label:"7 days",   days:7   },
  { id:"14d", label:"14 days",  days:14  },
  { id:"30d", label:"30 days",  days:30  },
  { id:"90d", label:"90 days",  days:90  },
  { id:"6m",  label:"6 months", days:183 },
];

export const BLOCKED_DOMAINS = [
  "machinelearningmastery.com","towardsdatascience.com","analyticsvidhya.com",
  "kdnuggets.com","geeksforgeeks.org","freecodecamp.org","hackernoon.com",
  "dev.to","hashnode.com","kaggle.com","paperswithcode.com","arxiv.org",
  "reddit.com","quora.com","stackoverflow.com","stackexchange.com",
  "ycombinator.com","news.ycombinator.com",
  "medium.com","substack.com","ghost.io","wordpress.com","blogspot.com",
  "tumblr.com","weebly.com","wix.com",
  "pypi.org","npmjs.com","github.com","gitlab.com","bitbucket.org",
  "amazon.com","aws.amazon.com","azure.microsoft.com","cloud.google.com",
  "cnblogs.com","habr.com","csdn.net","segmentfault.com","juejin.cn",
  "wwwhatsnew.com","xataka.com",
  "youtube.com","youtu.be","vimeo.com","dailymotion.com",
];

export const BOOLEAN_QUERIES = {
  "Cohere":              `"Cohere" NOT "incoherent" NOT "cohere with"`,
  "Reka":                `("Reka" OR "reka.ai") AND ("AI" OR "LLM" OR "multimodal" OR "startup") NOT "reka dance"`,
  "Writer":              `"Writer" AND ("AI" OR "enterprise" OR "LLM" OR "startup") NOT "screenwriter" NOT "writer's block"`,
  "You.com":             `"You.com" AND ("AI" OR "search" OR "assistant")`,
  "Hebbia":              `"Hebbia" AND ("AI" OR "search" OR "enterprise" OR "knowledge")`,
  "Twelve Labs":         `"Twelve Labs" AND ("AI" OR "video" OR "search" OR "understanding")`,
  "Waabi":               `"Waabi" AND ("AI" OR "autonomous" OR "trucking" OR "self-driving")`,
  "DatologyAI":          `("DatologyAI" OR "Datology AI") AND ("AI" OR "data" OR "curation" OR "LLM")`,
  "V7":                  `"V7" AND ("AI" OR "computer vision" OR "annotation" OR "data") NOT "V7 car" NOT "V7 rocket"`,
  "Delphina":            `"Delphina" AND ("AI" OR "machine learning" OR "AutoML" OR "data") NOT "ship" NOT "hotel"`,
  "Crusoe":              `"Crusoe" AND ("AI" OR "cloud" OR "compute" OR "GPU" OR "infrastructure")`,
  "Unblocked":           `"Unblocked" AND ("AI" OR "developer" OR "engineering" OR "knowledge")`,
  "P-1 AI":              `("P-1 AI" OR "P1 AI") AND ("AI" OR "coding" OR "software agent" OR "developer")`,
  "Ricursive Intelligence": `"Ricursive" AND ("AI" OR "agent" OR "reasoning" OR "intelligence")`,
  "Artificial Agency":   `"Artificial Agency" AND ("AI" OR "gaming" OR "NPC" OR "characters")`,
  "Vizcom":              `"Vizcom" AND ("AI" OR "design" OR "render" OR "sketch")`,
  "Yutori":              `"Yutori" AND ("AI" OR "search" OR "research" OR "agent") NOT "fashion" NOT "clothing"`,
  "Firsthand":           `"Firsthand" AND "rubenstein" AND ("AI" OR "agent" OR "brand" OR "advertising") NOT "experience" NOT "account"`,
  "Spara":               `"Spara" AND ("AI" OR "sales" OR "revenue" OR "pipeline") NOT "spare"`,
  "Emerald AI":          `("Emerald AI") OR ("Emerald" AND ("workflow automation" OR "business systems" OR "enterprise AI")) NOT "Emerald Isle" NOT "Emerald City" NOT "Emerald Group"`,
  "Mosaic":              `"Mosaic" AND ("AI" OR "finance" OR "FP&A" OR "planning") NOT "tile" NOT "theory" NOT "law"`,
  "Outset":              `"Outset" AND ("AI" OR "research" OR "qualitative" OR "interviews")`,
  "World Labs":          `"World Labs" AND ("AI" OR "spatial" OR "Fei-Fei Li" OR "3D")`,
  "OffDeal":             `"OffDeal" AND ("AI" OR "acquisition" OR "M&A" OR "business")`,
  "Aspect Biosystems":   `"Aspect Biosystems" AND ("bioprinting" OR "tissue" OR "healthcare" OR "biotech")`,
  "Genesis Molecular AI":`("Genesis Therapeutics" OR "Genesis Molecular") AND ("AI" OR "drug discovery" OR "molecular" OR "biotech")`,
  "PocketHealth":        `"PocketHealth" AND ("medical" OR "imaging" OR "radiology" OR "patient")`,
  "Signal 1":            `"Signal 1" AND ("AI" OR "healthcare" OR "hospital" OR "patient") NOT "signal one"`,
  "Ubenwa":              `"Ubenwa" AND ("AI" OR "infant" OR "cry" OR "diagnostics")`,
  "Unlearn":             `"Unlearn" AND ("AI" OR "clinical trial" OR "digital twin" OR "healthcare")`,
  "Intrepid Labs":       `"Intrepid Labs" AND ("AI" OR "biomarker" OR "neurological" OR "healthcare")`,
  "Slingshot AI":        `"Slingshot AI" AND ("AI" OR "medical" OR "scribe" OR "documentation")`,
  "Ribbon":              `"Ribbon Health" AND ("healthcare" OR "navigation" OR "provider" OR "data")`,
  "Attuned Intelligence":`"Attuned" AND ("AI" OR "wellbeing" OR "mental health" OR "emotional")`,
  "Nabla Bio":           `"Nabla Bio" AND ("protein design" OR "protein engineering" OR "nabla.bio" OR "generative biology" OR "de novo protein")`,
  "Chemix":              `"Chemix" AND ("AI" OR "battery" OR "materials" OR "energy")`,
  "ClimateAi":           `"ClimateAi" AND ("AI" OR "climate" OR "agriculture" OR "weather")`,
  "Orbital Materials":   `"Orbital Materials" AND ("AI" OR "materials" OR "discovery")`,
  "Latent Labs":         `"Latent Labs" AND ("AI" OR "protein" OR "biology" OR "generative")`,
  "Periodic Labs":       `"Periodic Labs" AND ("scientific AI" OR "literature synthesis" OR "periodiclabs.ai" OR "hypothesis generation" OR "research AI")`,
  "Muon Space":          `"Muon Space" AND ("satellite" OR "climate" OR "Earth observation")`,
  "Pixxel":              `"Pixxel" AND ("satellite" OR "imaging" OR "Earth" OR "hyperspectral")`,
  "Xanadu":              `"Xanadu" AND ("AI" OR "quantum" OR "computing" OR "photonic")`,
  "Promise Robotics":    `"Promise Robotics" AND ("robotics" OR "construction" OR "automation")`,
  "Synex":               `"Synex" AND ("AI" OR "cell therapy" OR "biotech" OR "manufacturing")`,
  "Serval":              `"Serval" AND ("AI" OR "security" OR "threat" OR "cyber") NOT "animal" NOT "cat"`,
  "Cinder":              `"Cinder" AND ("AI" OR "trust" OR "safety" OR "moderation" OR "cinder.ai") NOT "cinders"`,
  "Decart":              `"Decart" AND ("AI" OR "training" OR "serving" OR "inference" OR "decart.ai")`,
  "Etched":              `"Etched" AND ("AI" OR "ASIC" OR "transformer" OR "silicon" OR "chip" OR "etched.com")`,
  "Prime Intellect":     `("Prime Intellect" OR "primeintellect.ai" OR "INTELLECT-1" OR "INTELLECT-2" OR "INTELLECT-3") AND ("AI" OR "compute" OR "training" OR "reinforcement learning" OR "post-training" OR "distributed" OR "agentic" OR "GPU")`,
  "Radical Ventures":    `("Radical Ventures" OR "radical.vc") AND ("AI" OR "venture" OR "fund" OR "investment" OR "portfolio" OR "startup" OR "founder") NOT "radical change" NOT "radical left" NOT "radical right" NOT "radical idea"`,
};

const RAW_PORTFOLIO = [
  { id:1,  name:"Cohere",           categories:["LLMs","Software"],                  year:2020, description:"Enterprise AI platform for language models — search, summarisation, and generation at scale.", website:"cohere.com",            twitter_handle:"Cohere",          twitter_accounts:["aidangomez","1vnzh","nickfrosst","JayAlammar"], competitors_seed:["Anthropic","OpenAI","Mistral AI"] },
  { id:2,  name:"Aspect Biosystems",categories:["Biotechnology","Healthcare"],       year:2020, description:"Bioprinting platform for creating living tissues with vascular networks for drug discovery.", website:"aspectbiosystems.com",  twitter_handle:"aspect_bio",      twitter_accounts:[], competitors_seed:["Organovo","CELLINK","Prellis Biologics"] },
  { id:3,  name:"Genesis Molecular AI",categories:["Biotechnology","Healthcare","Materials"],year:2020,description:"AI-native small molecule drug discovery platform using physics-based molecular simulation.", website:"genesistherapeutics.ai",twitter_handle:"GenesisMolAI",    twitter_accounts:["enfeinberg"], competitors_seed:["Schrödinger","Recursion Pharmaceuticals","Insilico Medicine"] },
  { id:4,  name:"PocketHealth",     categories:["Healthcare"],                       year:2020, description:"Patient-controlled medical imaging platform — patients own and share their radiology records.", website:"pockethealth.com",     twitter_handle:"PocketHealth",    twitter_accounts:[], competitors_seed:["Ambra Health","Nanox","Intelerad"] },
  { id:5,  name:"Promise Robotics", categories:["Construction","Robotics","Supply Chain"],year:2020,description:"AI-powered robotic platform for automating off-site construction of building structures.", website:"promiserobotics.com",   twitter_handle:"PromiseRobotics", twitter_accounts:["ramtin_attar"], competitors_seed:["ICON Build","Mighty Buildings","Skender"] },
  { id:6,  name:"Synex",            categories:["Biotechnology","Healthcare"],       year:2020, description:"Cell therapy manufacturing platform using AI to scale and optimise complex cell production.", website:"synex.bio",             twitter_handle:"synexmedical",    twitter_accounts:[], competitors_seed:["Ori Biotech","Multiply Labs","Cellares"] },
  { id:7,  name:"Chemix",           categories:["Climate","Energy","Materials"],     year:2021, description:"AI platform for designing next-generation battery electrolytes and energy storage materials.", website:"chemix.ai",             twitter_handle:"ChemixAI",        twitter_accounts:[], competitors_seed:["Aionics","Sila Nanotechnologies","QuantumScape"] },
  { id:8,  name:"ClimateAi",        categories:["Climate","Supply Chain"],           year:2021, description:"Climate risk intelligence platform for agriculture and supply chain using hyperlocal AI forecasting.", website:"climate.ai",        twitter_handle:"climate_ai",      twitter_accounts:[], competitors_seed:["The Climate Corporation","aWhere","Gro Intelligence"] },
  { id:9,  name:"Waabi",            categories:["Data","Supply Chain","Transportation"],year:2021,description:"AI-first autonomous trucking company using a generative world model to train and deploy self-driving trucks.", website:"waabi.ai",twitter_handle:"Waabi_AI",        twitter_accounts:["RaquelUrtasun"], competitors_seed:["Aurora Innovation","TuSimple","Kodiak Robotics"] },
  { id:10, name:"Hebbia",           categories:["Financial Services","LLMs","Search","Software"],year:2022,description:"AI research platform for knowledge work — structured analysis of complex documents at enterprise scale.", website:"hebbia.ai",twitter_handle:"hebbiaai",        twitter_accounts:["gsivulka"], competitors_seed:["Glean","Perplexity","Kensho"] },
  { id:11, name:"Muon Space",       categories:["Software","Space"],                 year:2022, description:"Full-stack satellite company building a constellation for continuous Earth observation and climate monitoring.", website:"muonspace.com",    twitter_handle:"muonspace",       twitter_accounts:["jonnydyer"], competitors_seed:["Planet Labs","Spire Global","HawkEye 360"] },
  { id:12, name:"Pixxel",           categories:["Climate","Software","Space"],       year:2022, description:"Hyperspectral Earth imaging satellite constellation for agriculture, environment and resource monitoring.", website:"pixxel.space",      twitter_handle:"PixxelSpace",     twitter_accounts:[], competitors_seed:["Planet Labs","Satellogic","BlackSky"] },
  { id:13, name:"Signal 1",         categories:["Healthcare"],                       year:2022, description:"AI early warning system for hospitals — predicts patient deterioration before critical events occur.", website:"signal1.ai",          twitter_handle:"Signal1AI",       twitter_accounts:[], competitors_seed:["Sepsis Alliance","Dascena","BioVitals"] },
  { id:14, name:"Twelve Labs",      categories:["Search","Software"],                year:2022, description:"Video understanding API — multimodal AI that can search, understand and generate insights from video content.", website:"twelvelabs.io",   twitter_handle:"twelve_labs",     twitter_accounts:["_jae_lee"], competitors_seed:["Runway","Google Video AI","Amazon Rekognition"] },
  { id:15, name:"Ubenwa",           categories:["Healthcare"],                       year:2022, description:"AI diagnostics platform that analyses infant cry patterns to detect neurological conditions at birth.", website:"ubenwa.ai",          twitter_handle:"UbenwaHealth",    twitter_accounts:[], competitors_seed:["Natus Medical","Masimo","Medtronic Newborn"] },
  { id:16, name:"Unlearn",          categories:["Data","Healthcare"],                year:2022, description:"AI platform that generates digital twin control arms to accelerate and de-risk clinical trials.", website:"unlearn.ai",          twitter_handle:"UnlearnAI",       twitter_accounts:[], competitors_seed:["Medidata Solutions","Inato","Phesi"] },
  { id:17, name:"V7",               categories:["Data","Software"],                  year:2022, description:"AI training data platform for computer vision — annotation, automation and data pipeline management.", website:"v7labs.com",         twitter_handle:"V7Labs",          twitter_accounts:[], competitors_seed:["Scale AI","Labelbox","Roboflow"] },
  { id:18, name:"Xanadu",           categories:["Semiconductors"],                   year:2019, description:"Photonic quantum computing company building fault-tolerant quantum computers using light.", website:"xanadu.ai",           twitter_handle:"XanaduAI",        twitter_accounts:["_cweedbrook"], competitors_seed:["IonQ","PsiQuantum","IBM Quantum"] },
  { id:19, name:"You.com",          categories:["LLMs","Search"],                    year:2022, description:"AI-powered search engine and productivity assistant with real-time web grounding.", website:"you.com",             twitter_handle:"YouSearchEngine", twitter_accounts:[], competitors_seed:["Perplexity AI","Bing AI","Google AI Overviews"] },
  { id:20, name:"Artificial Agency",categories:["Software"],                         year:2023, description:"AI agent platform for game NPCs — enabling believable, adaptive, LLM-powered non-player characters.", website:"artificialagency.ai",twitter_handle:"artificialagency",twitter_accounts:["kongaloosh"], competitors_seed:["Inworld AI","Convai","NVIDIA ACE"] },
  { id:21, name:"DatologyAI",       categories:["Data"],                             year:2023, description:"Automated data curation platform — curates and optimises training datasets to improve LLM quality.", website:"datology.ai",        twitter_handle:"DatologyAI",      twitter_accounts:["arimorcos"], competitors_seed:["Scale AI","Gretel AI","Snorkel AI"] },
  { id:22, name:"Delphina",         categories:["Data","Software"],                  year:2023, description:"Automated ML pipeline platform — finds the best models and features for tabular data without manual work.", website:"delphina.ai",       twitter_handle:"delphina_ai",     twitter_accounts:[], competitors_seed:["DataRobot","H2O.ai","Alteryx"] },
  { id:23, name:"Firsthand",        categories:["Software"],                         year:2023, description:"Personal AI that knows your preferences and acts on your behalf for commerce and services.", website:"firsthand.ai",       twitter_handle:"",                twitter_accounts:[], competitors_seed:["Rabbit","Humane","Adept AI"] },
  { id:24, name:"Intrepid Labs",    categories:["Healthcare"],                       year:2023, description:"AI biomarker discovery platform for neurological diseases using multimodal patient data.", website:"intrepidlabs.ai",    twitter_handle:"IntrepidLabs",    twitter_accounts:[], competitors_seed:["Praxis Precision Medicine","Tempus","Recursion"] },
  { id:25, name:"Nabla Bio",        categories:["Biotechnology","Materials"],        year:2023, description:"Protein design platform using generative AI to engineer novel proteins for therapeutic and industrial uses.", website:"nabla.bio",          twitter_handle:"NablaBio",        twitter_accounts:["SurgeBiswas"], competitors_seed:["Absci","Arzeda","Generate Biomedicines"] },
  { id:26, name:"Orbital Materials",categories:["Climate","Materials"],              year:2023, description:"AI foundation model for materials discovery — accelerating the design of new sustainable materials.", website:"orbitalmaterials.com",twitter_handle:"OrbitalHardware",  twitter_accounts:["jgodwin_ai"], competitors_seed:["Citrine Informatics","Kebotix","Enthought"] },
  { id:27, name:"Reka",             categories:["LLMs","Software"],                  year:2023, description:"Multimodal frontier AI company building powerful models for enterprise and consumer applications.", website:"reka.ai",             twitter_handle:"Reka_AI",         twitter_accounts:["DaniYogatama"], competitors_seed:["Mistral AI","Cohere","Inflection AI"] },
  { id:28, name:"Emerald AI",       categories:["Software"],                         year:2024, description:"AI platform for enterprise workflow automation with deep integration into existing business systems.", website:"emeraldai.com",      twitter_handle:"",                twitter_accounts:[], competitors_seed:["UiPath","Automation Anywhere","ServiceNow AI"] },
  { id:29, name:"Latent Labs",      categories:["Biotechnology","Software"],         year:2024, description:"Generative AI for protein structure and function — foundation models for biological sequence design.", website:"latentlabs.ai",     twitter_handle:"latentlabs_ai",   twitter_accounts:["saakohl"], competitors_seed:["EvolutionaryScale","Generate Biomedicines","Profluent"] },
  { id:30, name:"OffDeal",          categories:["Financial Services","Software"],    year:2024, description:"AI platform for SMB M&A — finding, analysing and executing acquisitions for small business buyers.", website:"offdeal.com",        twitter_handle:"offdeal_ai",      twitter_accounts:["leveredvlad"], competitors_seed:["Axial","Exitwise","BizBuySell"] },
  { id:31, name:"Spara",            categories:["Software"],                         year:2024, description:"AI-powered revenue intelligence platform for B2B sales teams — pipeline and deal execution.", website:"spara.ai",            twitter_handle:"SparaAI",         twitter_accounts:[], competitors_seed:["Gong","Clari","Outreach"] },
  { id:32, name:"World Labs",       categories:["Software"],                         year:2024, description:"Spatial intelligence company building large world models for 3D understanding and generation.", website:"worldlabs.ai",      twitter_handle:"worldlabs_ai",    twitter_accounts:["drfeifei","jcjohnss","BenMildenhall","chlassner"], competitors_seed:["Waymo Research","DeepMind","NVIDIA Research"] },
  { id:33, name:"Writer",           categories:["LLMs","Software"],                  year:2024, description:"Full-stack generative AI for the enterprise — models, platform and applications for business content.", website:"writer.com",          twitter_handle:"Writer",          twitter_accounts:["mayhabib"], competitors_seed:["Jasper AI","Copy.ai","Anthropic Claude"] },
  { id:34, name:"Attuned Intelligence",categories:["Healthcare"],                    year:2025, description:"AI system for detecting and supporting emotional and cognitive wellbeing in clinical settings.", website:"attuned-intelligence.com",          twitter_handle:"AttunedAI",       twitter_accounts:[], competitors_seed:["Woebot","Limbic","Spring Health"] },
  { id:35, name:"Crusoe",           categories:["Infrastructure"],                   year:2025, description:"Sustainable cloud computing platform using stranded and renewable energy for AI workloads.", website:"crusoe.ai",           twitter_handle:"Crusoe",          twitter_accounts:["ChaseLochmiller"], competitors_seed:["CoreWeave","Lambda Labs","Voltage Park"] },
  { id:36, name:"Mosaic",           categories:["Financial Services","Software"],    year:2026, description:"AI-native financial planning and analysis platform for modern finance teams.", website:"mosaicapp.com",      twitter_handle:"mosaic_video",    twitter_accounts:[], competitors_seed:["Pigment","Planful","Anaplan"] },
  { id:37, name:"Outset",           categories:["Software"],                         year:2025, description:"AI-powered qualitative research platform — conducts and analyses user interviews at scale.", website:"outset.ai",           twitter_handle:"outset_ai",       twitter_accounts:["AaronLCannon"], competitors_seed:["UserInterviews","Maze","Respondent"] },
  { id:38, name:"P-1 AI",           categories:["Software"],                         year:2025, description:"AI coding agent that autonomously writes, tests and deploys production software end-to-end.", website:"p1.ai",              twitter_handle:"P1_AI",           twitter_accounts:["PaulEremenko"], competitors_seed:["Devin (Cognition)","GitHub Copilot","Cursor"] },
  { id:39, name:"Periodic Labs",    categories:["Software"],                         year:2025, description:"AI platform for scientific literature synthesis and hypothesis generation in research workflows.", website:"periodiclabs.ai",    twitter_handle:"PeriodicLabs",    twitter_accounts:["LiamFedus"], competitors_seed:["Elicit","Consensus","Semantic Scholar"] },
  { id:40, name:"Ricursive Intelligence",categories:["Infrastructure","Software"],   year:2025, description:"Recursive AI infrastructure for self-improving agent systems and autonomous reasoning at scale.", website:"ricursive.ai",      twitter_handle:"RicursiveAI",     twitter_accounts:["annadgoldie","Azaliamirh"], competitors_seed:["LangChain","CrewAI","AutoGPT"] },
  { id:41, name:"Ribbon",           categories:["Software"],                         year:2025, description:"AI-powered healthcare navigation platform — helping patients find and access the right care.", website:"ribbon.health",      twitter_handle:"ribbon_ai",       twitter_accounts:["davevu23","arshamg_"], competitors_seed:["Kyruus","Solv Health","Zocdoc"] },
  { id:42, name:"Serval",           categories:["Software","Security"],              year:2025, description:"AI security platform for autonomous threat detection and response in enterprise environments.", website:"serval.ai",           twitter_handle:"ServalAI",        twitter_accounts:[], competitors_seed:["Darktrace","SentinelOne","CrowdStrike"] },
  { id:43, name:"Slingshot AI",     categories:["Healthcare"],                       year:2025, description:"AI-powered clinical documentation platform — automated notes and coding for healthcare providers.", website:"slingshotai.com",    twitter_handle:"slingshot_ai",    twitter_accounts:["neilparikh","danielreidcahn"], competitors_seed:["Nuance DAX","Abridge","Suki AI"] },
  { id:44, name:"Unblocked",        categories:["Software"],                         year:2025, description:"AI knowledge assistant for engineering teams — surfaces institutional knowledge from codebases and docs.", website:"getunblocked.com",  twitter_handle:"GetUnblocked",    twitter_accounts:[], competitors_seed:["Glean","Notion AI","Guru"] },
  { id:45, name:"Vizcom",           categories:["Software"],                         year:2025, description:"AI design tool for industrial designers — generates photorealistic product renders from sketches.", website:"vizcom.ai",          twitter_handle:"vizcom_ai",       twitter_accounts:["Aquahugs"], competitors_seed:["Midjourney","Adobe Firefly","Canva AI"] },
  { id:46, name:"Yutori",           categories:["Search","Software"],                year:2025, description:"AI agent for autonomous web search and deep research — executes complex multi-step research tasks.", website:"yutori.ai",          twitter_handle:"yutori_ai",       twitter_accounts:["deviparikh","DhruvBatra_","abhshkdz"], competitors_seed:["Perplexity","You.com","OpenAI Deep Research"] },
  { id:47, name:"Decart",           categories:["Infrastructure","Software"],        year:2024, description:"AI infrastructure platform for ultra-fast model training and serving, focusing on inference efficiency.", website:"decart.ai",         twitter_handle:"DecartAI",        twitter_accounts:["DLeitersdorf","mshaleveg"], competitors_seed:["NVIDIA","Groq","Together AI"] },
  { id:48, name:"Etched",           categories:["Semiconductors"],                   year:2024, description:"Semiconductor company building specialized ASICs designed specifically for transformer-based models.", website:"etched.com",         twitter_handle:"Etched",          twitter_accounts:["UbertiGavin"], competitors_seed:["NVIDIA","Cerebras","SambaNova"] },
  { id:49, name:"Cinder",           categories:["Software","Security"],              year:2024, description:"Trust and safety platform using AI to manage content moderation and policy enforcement at scale.", website:"cinder.ai",          twitter_handle:"cinder_ai",       twitter_accounts:["itsGlenWise"], competitors_seed:["ActiveFence","Unitary","Spectrum Labs"] },
  { id:50, name:"Prime Intellect",  categories:["Infrastructure","Software"],        year:2024, description:"Compute and infrastructure platform for RL-based post-training — enables teams to train, evaluate and deploy custom agentic models at scale using distributed GPU clusters.", website:"primeintellect.ai",  twitter_handle:"PrimeIntellect",  twitter_accounts:["vincentweisser"], competitors_seed:["Together AI","Anyscale","Modal","Lambda Labs","Scale AI"] },
  { id:52, name:"Sequrity",         categories:["Software","Security"],              year:2024, description:"AI-native cybersecurity platform for identifying and remediating vulnerabilities in AI and ML systems.", website:"sequrity.ai",        twitter_handle:"SequrityAI",      twitter_accounts:["iliaishacked"], competitors_seed:["Protect AI","HiddenLayer","CalypsoAI"] },
  { id:99, name:"Radical Ventures", categories:["VC"], isFirm:true,                  year:2017, description:"AI-focused venture capital fund backing the world's most ambitious AI founders from seed to growth.", website:"radical.vc",           twitter_handle:"radical_vc",      twitter_accounts:[], competitors_seed:["Sequoia Capital","a16z","Khosla Ventures","General Catalyst","Coatue"] },
];

export function buildInitialCompanies() {
  return RAW_PORTFOLIO.map(c => ({
    id: c.id,
    name: c.name,
    categories: c.categories,
    year: c.year,
    description: c.description,
    website: c.website,
    ...(c.isFirm ? { isFirm: true } : {}),
    twitter_handle: c.twitter_handle || "",
    twitter_accounts: c.twitter_accounts || [],
    enabled: true,
    boolean_query: BOOLEAN_QUERIES[c.name] || `"${c.name}"`,
    boolean_approved: Boolean(BOOLEAN_QUERIES[c.name]),
    competitors: (c.competitors_seed || []).map(name => ({
      id: `comp-${c.id}-${name.replace(/\W+/g, "")}`,
      name,
      rationale: "",
    })),
    runs: [],
    sovRun: null,
  }));
}

export const DEFAULT_OUTLETS = [
  // ── Tier 1: Global News & Business ──────────────────────────────────────────
  {id:1,   name:"The New York Times",              tier:1, cat:"General",     domain:"nytimes.com"},
  {id:2,   name:"The Wall Street Journal",         tier:1, cat:"General",     domain:"wsj.com"},
  {id:3,   name:"Bloomberg",                       tier:1, cat:"General",     domain:"bloomberg.com"},
  {id:4,   name:"Financial Times",                 tier:1, cat:"General",     domain:"ft.com"},
  {id:5,   name:"The Economist",                   tier:1, cat:"General",     domain:"economist.com"},
  {id:6,   name:"Reuters",                         tier:1, cat:"General",     domain:"reuters.com"},
  {id:7,   name:"BBC News",                        tier:1, cat:"General",     domain:"bbc.com"},
  {id:8,   name:"The Guardian",                    tier:1, cat:"General",     domain:"theguardian.com"},
  {id:9,   name:"CNBC",                            tier:1, cat:"General",     domain:"cnbc.com"},
  {id:10,  name:"Forbes",                          tier:1, cat:"General",     domain:"forbes.com"},
  {id:11,  name:"Fortune",                         tier:1, cat:"General",     domain:"fortune.com"},
  {id:12,  name:"The Atlantic",                    tier:1, cat:"General",     domain:"theatlantic.com"},
  {id:13,  name:"Associated Press",                tier:1, cat:"General",     domain:"apnews.com"},
  {id:14,  name:"The Washington Post",             tier:1, cat:"General",     domain:"washingtonpost.com"},
  {id:15,  name:"Business Insider",                tier:1, cat:"General",     domain:"businessinsider.com"},
  {id:16,  name:"Yahoo Finance",                   tier:1, cat:"Finance",     domain:"finance.yahoo.com"},
  {id:17,  name:"MarketWatch",                     tier:1, cat:"Finance",     domain:"marketwatch.com"},
  {id:18,  name:"Barron's",                        tier:1, cat:"Finance",     domain:"barrons.com"},
  {id:19,  name:"South China Morning Post",        tier:1, cat:"General",     domain:"scmp.com"},
  {id:20,  name:"Nikkei Asia",                     tier:1, cat:"General",     domain:"asia.nikkei.com"},
  {id:21,  name:"The Australian Financial Review", tier:1, cat:"Finance",     domain:"afr.com"},
  {id:22,  name:"Inc.",                            tier:1, cat:"Startups",    domain:"inc.com"},
  {id:23,  name:"Time",                            tier:1, cat:"General",     domain:"time.com"},
  {id:24,  name:"Newsweek",                        tier:1, cat:"General",     domain:"newsweek.com"},
  {id:25,  name:"Harvard Business Review",         tier:1, cat:"Business",    domain:"hbr.org"},
  {id:26,  name:"USA Today",                       tier:1, cat:"General",     domain:"usatoday.com"},
  {id:27,  name:"The New Yorker",                  tier:1, cat:"General",     domain:"newyorker.com"},
  {id:28,  name:"Politico",                        tier:1, cat:"Policy",      domain:"politico.com"},
  {id:29,  name:"Seeking Alpha",                   tier:1, cat:"Finance",     domain:"seekingalpha.com"},
  {id:30,  name:"Investor's Business Daily",       tier:1, cat:"Finance",     domain:"investors.com"},
  {id:31,  name:"TheStreet",                       tier:1, cat:"Finance",     domain:"thestreet.com"},
  {id:32,  name:"Institutional Investor",          tier:1, cat:"Finance",     domain:"institutionalinvestor.com"},
  {id:33,  name:"MIT Sloan Management Review",     tier:1, cat:"Business",    domain:"sloanreview.mit.edu"},
  {id:34,  name:"Quartz",                          tier:1, cat:"Business",    domain:"qz.com"},
  {id:35,  name:"McKinsey Quarterly",              tier:1, cat:"Business",    domain:"mckinsey.com"},
  {id:36,  name:"Los Angeles Times",               tier:1, cat:"General",     domain:"latimes.com"},
  {id:37,  name:"The Globe and Mail",              tier:1, cat:"Canada",      domain:"theglobeandmail.com"},
  {id:38,  name:"Axios",                           tier:1, cat:"Tech",        domain:"axios.com"},
  // ── Tier 1: Science & Research ──────────────────────────────────────────────
  {id:50,  name:"Nature",                          tier:1, cat:"Science",     domain:"nature.com"},
  {id:51,  name:"Science",                         tier:1, cat:"Science",     domain:"science.org"},
  {id:52,  name:"Nature Machine Intelligence",     tier:1, cat:"AI",          domain:"nature.com"},
  {id:53,  name:"Scientific American",             tier:1, cat:"Science",     domain:"scientificamerican.com"},
  {id:54,  name:"Quanta Magazine",                 tier:1, cat:"Science",     domain:"quantamagazine.org"},
  {id:55,  name:"MIT Technology Review",           tier:1, cat:"Tech",        domain:"technologyreview.com"},
  // ── Tier 2: Core Tech ───────────────────────────────────────────────────────
  {id:100, name:"TechCrunch",                      tier:2, cat:"Tech",        domain:"techcrunch.com"},
  {id:101, name:"Wired",                           tier:2, cat:"Tech",        domain:"wired.com"},
  {id:102, name:"VentureBeat",                     tier:2, cat:"Tech",        domain:"venturebeat.com"},
  {id:103, name:"The Verge",                       tier:2, cat:"Tech",        domain:"theverge.com"},
  {id:104, name:"Ars Technica",                    tier:2, cat:"Tech",        domain:"arstechnica.com"},
  {id:105, name:"IEEE Spectrum",                   tier:2, cat:"Tech",        domain:"spectrum.ieee.org"},
  {id:106, name:"CNET",                            tier:2, cat:"Tech",        domain:"cnet.com"},
  {id:107, name:"ZDNet",                           tier:2, cat:"Tech",        domain:"zdnet.com"},
  {id:108, name:"GeekWire",                        tier:2, cat:"Tech",        domain:"geekwire.com"},
  {id:109, name:"Fast Company",                    tier:2, cat:"Tech",        domain:"fastcompany.com"},
  {id:110, name:"Sifted",                          tier:2, cat:"Tech",        domain:"sifted.eu"},
  {id:111, name:"Engadget",                        tier:2, cat:"Tech",        domain:"engadget.com"},
  {id:112, name:"The Information",                 tier:2, cat:"Tech",        domain:"theinformation.com"},
  {id:113, name:"The Register",                    tier:2, cat:"Tech",        domain:"theregister.com"},
  {id:114, name:"SiliconANGLE",                    tier:2, cat:"Tech",        domain:"siliconangle.com"},
  {id:115, name:"TechRepublic",                    tier:2, cat:"Tech",        domain:"techrepublic.com"},
  {id:116, name:"Computerworld",                   tier:2, cat:"Tech",        domain:"computerworld.com"},
  {id:117, name:"InfoQ",                           tier:2, cat:"Tech",        domain:"infoq.com"},
  {id:118, name:"InformationWeek",                 tier:2, cat:"Tech",        domain:"informationweek.com"},
  {id:119, name:"CRN",                             tier:2, cat:"Tech",        domain:"crn.com"},
  {id:120, name:"Tom's Hardware",                  tier:2, cat:"Tech",        domain:"tomshardware.com"},
  {id:121, name:"PCMag",                           tier:2, cat:"Tech",        domain:"pcmag.com"},
  {id:122, name:"Digital Trends",                  tier:2, cat:"Tech",        domain:"digitaltrends.com"},
  {id:123, name:"Gizmodo",                         tier:2, cat:"Tech",        domain:"gizmodo.com"},
  {id:124, name:"Mashable",                        tier:2, cat:"Tech",        domain:"mashable.com"},
  {id:125, name:"Rest of World",                   tier:2, cat:"Tech",        domain:"restofworld.org"},
  {id:126, name:"Protocol",                        tier:2, cat:"Tech",        domain:"protocol.com"},
  {id:127, name:"Morning Brew",                    tier:2, cat:"Business",    domain:"morningbrew.com"},
  {id:128, name:"The Hustle",                      tier:2, cat:"Business",    domain:"thehustle.co"},
  {id:129, name:"Network World",                   tier:2, cat:"Tech",        domain:"networkworld.com"},
  {id:130, name:"CIO",                             tier:2, cat:"Tech",        domain:"cio.com"},
  {id:131, name:"TechTarget",                      tier:2, cat:"Tech",        domain:"techtarget.com"},
  {id:132, name:"Digiday",                         tier:2, cat:"Tech",        domain:"digiday.com"},
  {id:133, name:"MacRumors",                       tier:2, cat:"Tech",        domain:"macrumors.com"},
  {id:134, name:"9to5Mac",                         tier:2, cat:"Tech",        domain:"9to5mac.com"},
  {id:135, name:"9to5Google",                      tier:2, cat:"Tech",        domain:"9to5google.com"},
  {id:136, name:"AppleInsider",                    tier:2, cat:"Tech",        domain:"appleinsider.com"},
  // ── Tier 2: VC, Investing & Startups ────────────────────────────────────────
  {id:150, name:"PitchBook",                       tier:2, cat:"VC",          domain:"pitchbook.com"},
  {id:151, name:"Crunchbase News",                 tier:2, cat:"VC",          domain:"news.crunchbase.com"},
  {id:152, name:"CB Insights",                     tier:2, cat:"VC",          domain:"cbinsights.com"},
  {id:153, name:"StrictlyVC",                      tier:2, cat:"VC",          domain:"strictlyvc.com"},
  {id:154, name:"The Deal",                        tier:2, cat:"VC",          domain:"thedeal.com"},
  {id:155, name:"Silicon Valley Business Journal", tier:2, cat:"VC",          domain:"bizjournals.com"},
  {id:156, name:"First Round Review",              tier:2, cat:"VC",          domain:"review.firstround.com"},
  {id:157, name:"NFX Essays",                      tier:2, cat:"VC",          domain:"nfx.com"},
  {id:158, name:"Both Sides of the Table",         tier:2, cat:"VC",          domain:"bothsidesofthetable.com"},
  {id:159, name:"Mattermark",                      tier:2, cat:"VC",          domain:"mattermark.com"},
  {id:160, name:"Startup Grind",                   tier:2, cat:"Startups",    domain:"startupgrind.com"},
  {id:161, name:"Hacker News",                     tier:2, cat:"Tech",        domain:"news.ycombinator.com"},
  {id:162, name:"Product Hunt",                    tier:2, cat:"Startups",    domain:"producthunt.com"},
  {id:163, name:"The Logic",                       tier:2, cat:"Canada",      domain:"thelogic.co"},
  {id:164, name:"BetaKit",                         tier:2, cat:"Canada",      domain:"betakit.com"},
  {id:165, name:"Financial Post",                  tier:2, cat:"Canada",      domain:"financialpost.com"},
  {id:166, name:"CBC News",                        tier:2, cat:"Canada",      domain:"cbc.ca"},
  // ── Tier 2: AI & Machine Learning ───────────────────────────────────────────
  {id:200, name:"The Decoder",                     tier:2, cat:"AI",          domain:"the-decoder.com"},
  {id:201, name:"The Gradient",                    tier:2, cat:"AI",          domain:"thegradient.pub"},
  {id:202, name:"Import AI",                       tier:2, cat:"AI"},
  {id:203, name:"The Rundown AI",                  tier:2, cat:"AI",          domain:"therundown.ai"},
  {id:204, name:"AI Business",                     tier:2, cat:"AI",          domain:"aibusiness.com"},
  {id:205, name:"MarkTechPost",                    tier:2, cat:"AI",          domain:"marktechpost.com"},
  {id:206, name:"Stratechery",                     tier:2, cat:"AI",          domain:"stratechery.com"},
  {id:207, name:"SemiAnalysis",                    tier:2, cat:"AI",          domain:"semianalysis.com"},
  {id:208, name:"Ben's Bites",                     tier:2, cat:"AI"},
  {id:209, name:"AlphaSignal",                     tier:2, cat:"AI",          domain:"alphasignal.ai"},
  {id:210, name:"Unite.AI",                        tier:2, cat:"AI",          domain:"unite.ai"},
  {id:211, name:"Synced",                          tier:2, cat:"AI",          domain:"syncedreview.com"},
  {id:212, name:"AI Trends",                       tier:2, cat:"AI",          domain:"aitrends.com"},
  {id:213, name:"Analytics India Magazine",        tier:2, cat:"AI",          domain:"analyticsindiamag.com"},
  {id:214, name:"The Sequence",                    tier:2, cat:"AI"},
  {id:215, name:"Interconnects",                   tier:2, cat:"AI",          domain:"interconnects.ai"},
  {id:216, name:"Last Week in AI",                 tier:2, cat:"AI",          domain:"lastweekin.ai"},
  {id:217, name:"The Neuron",                      tier:2, cat:"AI"},
  {id:218, name:"Emerj",                           tier:2, cat:"AI",          domain:"emerj.com"},
  {id:219, name:"AI Magazine",                     tier:2, cat:"AI",          domain:"aimagazine.com"},
  {id:220, name:"The Batch",                       tier:2, cat:"AI",          domain:"deeplearning.ai"},
  {id:221, name:"TLDR AI",                         tier:2, cat:"AI",          domain:"tldr.tech"},
  {id:222, name:"Ahead of AI",                     tier:2, cat:"AI"},
  {id:223, name:"The Algorithmic Bridge",          tier:2, cat:"AI"},
  {id:224, name:"AI Snake Oil",                    tier:2, cat:"AI",          domain:"aisnakeoil.com"},
  {id:225, name:"Hugging Face Blog",               tier:2, cat:"AI",          domain:"huggingface.co"},
  {id:226, name:"OpenAI Blog",                     tier:2, cat:"AI",          domain:"openai.com"},
  {id:227, name:"Google DeepMind Blog",            tier:2, cat:"AI",          domain:"deepmind.google"},
  {id:228, name:"Anthropic Blog",                  tier:2, cat:"AI",          domain:"anthropic.com"},
  {id:229, name:"Meta AI Blog",                    tier:2, cat:"AI",          domain:"ai.meta.com"},
  {id:230, name:"Microsoft Research Blog",         tier:2, cat:"AI",          domain:"microsoft.com"},
  {id:231, name:"Berkeley AI Research Blog",       tier:2, cat:"AI",          domain:"bair.berkeley.edu"},
  {id:232, name:"Weights & Biases Blog",           tier:2, cat:"AI",          domain:"wandb.ai"},
  // ── Tier 2: Cloud, Enterprise & Infrastructure ──────────────────────────────
  {id:240, name:"Data Center Knowledge",           tier:2, cat:"Cloud",       domain:"datacenterknowledge.com"},
  {id:241, name:"Datacenter Dynamics",             tier:2, cat:"Cloud",       domain:"datacenterdynamics.com"},
  {id:242, name:"HPCwire",                         tier:2, cat:"Cloud",       domain:"hpcwire.com"},
  {id:243, name:"The Next Platform",               tier:2, cat:"Cloud",       domain:"nextplatform.com"},
  {id:244, name:"Inside HPC",                      tier:2, cat:"Cloud",       domain:"insidehpc.com"},
  {id:245, name:"Cloud Computing News",            tier:2, cat:"Cloud",       domain:"cloudcomputing-news.net"},
  {id:246, name:"Databricks Blog",                 tier:2, cat:"Cloud",       domain:"databricks.com"},
  {id:247, name:"Snowflake Blog",                  tier:2, cat:"Cloud",       domain:"snowflake.com"},
  // ── Tier 2: Semiconductors & Hardware ───────────────────────────────────────
  {id:250, name:"Semiconductor Engineering",       tier:2, cat:"Chips",       domain:"semiengineering.com"},
  {id:251, name:"EE Times",                        tier:2, cat:"Chips",       domain:"eetimes.com"},
  {id:252, name:"The Chip Letter",                 tier:2, cat:"Chips"},
  {id:253, name:"AnandTech",                       tier:2, cat:"Chips",       domain:"anandtech.com"},
  {id:254, name:"Electronic Design",               tier:2, cat:"Chips",       domain:"electronicdesign.com"},
  {id:255, name:"EDN",                             tier:2, cat:"Chips",       domain:"edn.com"},
  {id:256, name:"Embedded.com",                    tier:2, cat:"Chips",       domain:"embedded.com"},
  // ── Tier 2: Finance & Fintech ────────────────────────────────────────────────
  {id:260, name:"Finextra",                        tier:2, cat:"Fintech",     domain:"finextra.com"},
  {id:261, name:"Finovate",                        tier:2, cat:"Fintech",     domain:"finovate.com"},
  {id:262, name:"American Banker",                 tier:2, cat:"Fintech",     domain:"americanbanker.com"},
  {id:263, name:"Banking Dive",                    tier:2, cat:"Fintech",     domain:"bankingdive.com"},
  {id:264, name:"Crowdfund Insider",               tier:2, cat:"Fintech",     domain:"crowdfundinsider.com"},
  {id:265, name:"The Block",                       tier:2, cat:"Fintech",     domain:"theblock.co"},
  {id:266, name:"Cointelegraph",                   tier:2, cat:"Fintech",     domain:"cointelegraph.com"},
  {id:267, name:"InvestorPlace",                   tier:2, cat:"Finance",     domain:"investorplace.com"},
  {id:268, name:"Morningstar",                     tier:2, cat:"Finance",     domain:"morningstar.com"},
  // ── Tier 2: Cybersecurity ────────────────────────────────────────────────────
  {id:270, name:"Cybersecurity Dive",              tier:2, cat:"Security",    domain:"cybersecuritydive.com"},
  {id:271, name:"Dark Reading",                    tier:2, cat:"Security",    domain:"darkreading.com"},
  {id:272, name:"Krebs on Security",               tier:2, cat:"Security",    domain:"krebsonsecurity.com"},
  {id:273, name:"SecurityWeek",                    tier:2, cat:"Security",    domain:"securityweek.com"},
  {id:274, name:"BleepingComputer",                tier:2, cat:"Security",    domain:"bleepingcomputer.com"},
  {id:275, name:"SC Magazine",                     tier:2, cat:"Security",    domain:"scmagazine.com"},
  {id:276, name:"Threatpost",                      tier:2, cat:"Security",    domain:"threatpost.com"},
  // ── Tier 2: Robotics & Autonomous Systems ───────────────────────────────────
  {id:280, name:"The Robot Report",                tier:2, cat:"Robotics",    domain:"therobotreport.com"},
  {id:281, name:"Robotics Business Review",        tier:2, cat:"Robotics",    domain:"roboticsbusinessreview.com"},
  {id:282, name:"IEEE Robotics & Automation",      tier:2, cat:"Robotics",    domain:"ieee.org"},
  {id:283, name:"Electrek",                        tier:2, cat:"Robotics",    domain:"electrek.co"},
  {id:284, name:"SpaceNews",                       tier:2, cat:"Space",       domain:"spacenews.com"},
  // ── Tier 2: Science & Research ───────────────────────────────────────────────
  {id:290, name:"New Scientist",                   tier:2, cat:"Science",     domain:"newscientist.com"},
  {id:291, name:"ScienceDaily",                    tier:2, cat:"Science",     domain:"sciencedaily.com"},
  {id:292, name:"Phys.org",                        tier:2, cat:"Science",     domain:"phys.org"},
  {id:293, name:"STAT News",                       tier:2, cat:"Healthcare",  domain:"statnews.com"},
  {id:294, name:"NEJM",                            tier:2, cat:"Healthcare",  domain:"nejm.org"},
  {id:295, name:"Fierce Biotech",                  tier:2, cat:"Healthcare",  domain:"fiercebiotech.com"},
  {id:296, name:"BioPharma Dive",                  tier:2, cat:"Healthcare",  domain:"biopharmadive.com"},
  {id:297, name:"MedCity News",                    tier:2, cat:"Healthcare",  domain:"medcitynews.com"},
  {id:298, name:"Rock Health",                     tier:2, cat:"Healthcare",  domain:"rockhealth.com"},
  // ── Tier 2: Climate & Energy ─────────────────────────────────────────────────
  {id:300, name:"CleanTechnica",                   tier:2, cat:"Climate",     domain:"cleantechnica.com"},
  {id:301, name:"Canary Media",                    tier:2, cat:"Climate",     domain:"canarymedia.com"},
  {id:302, name:"Carbon Brief",                    tier:2, cat:"Climate",     domain:"carbonbrief.org"},
  {id:303, name:"GreenBiz",                        tier:2, cat:"Climate",     domain:"greenbiz.com"},
  {id:304, name:"E&E News",                        tier:2, cat:"Climate",     domain:"eenews.net"},
  {id:305, name:"Supply Chain Dive",               tier:2, cat:"Business",    domain:"supplychaindive.com"},
  {id:306, name:"Industry Week",                   tier:2, cat:"Business",    domain:"industryweek.com"},
  // ── Tier 3: AI Newsletters & Analysts ───────────────────────────────────────
  {id:500, name:"Benedict Evans",                  tier:3, cat:"Analysis",    domain:"ben-evans.com"},
  {id:501, name:"Not Boring",                      tier:3, cat:"Analysis",    domain:"notboring.co"},
  {id:502, name:"The Diff",                        tier:3, cat:"Analysis",    domain:"thediff.co"},
  {id:503, name:"Lenny's Newsletter",              tier:3, cat:"Analysis",    domain:"lennysnewsletter.com"},
  {id:504, name:"TLDR Newsletter",                 tier:3, cat:"Analysis",    domain:"tldr.tech"},
  {id:505, name:"Stratosphere",                    tier:3, cat:"Analysis",    domain:"stratosphere.io"},
  {id:506, name:"Daring Fireball",                 tier:3, cat:"Analysis",    domain:"daringfireball.net"},
  {id:507, name:"Asymco",                          tier:3, cat:"Analysis",    domain:"asymco.com"},
  {id:508, name:"Monday Note",                     tier:3, cat:"Analysis",    domain:"mondaynote.com"},
  {id:509, name:"Nathan.ai (Air Street Capital)",  tier:3, cat:"AI"},
  {id:510, name:"Ahead of AI (Sebastian Raschka)", tier:3, cat:"AI"},
  {id:511, name:"Gradient Dissent",                tier:3, cat:"AI",          domain:"wandb.ai"},
  {id:512, name:"MLOps Community",                 tier:3, cat:"AI",          domain:"mlops.community"},
  {id:513, name:"AI Supremacy",                    tier:3, cat:"AI"},
  {id:514, name:"The AI Report",                   tier:3, cat:"AI"},
  {id:515, name:"Chip Huyen's Blog",               tier:3, cat:"AI"},
  {id:516, name:"Andrej Karpathy's Blog",          tier:3, cat:"AI"},
  {id:517, name:"Eugene Yan's Blog",               tier:3, cat:"AI"},
  {id:518, name:"Hamel Husain's Blog",             tier:3, cat:"AI"},
  {id:519, name:"Papers With Code Blog",           tier:3, cat:"AI",          domain:"paperswithcode.com"},
  {id:520, name:"AI Breakfast",                    tier:3, cat:"AI"},
  {id:521, name:"Superhuman AI",                   tier:3, cat:"AI"},
  {id:522, name:"The Algorithmic Bridge (A.Xianopolous)", tier:3, cat:"AI"},
  {id:523, name:"Hardware Lottery",                tier:3, cat:"AI"},
  {id:524, name:"MIT News",                        tier:3, cat:"Research",    domain:"news.mit.edu"},
  {id:525, name:"Stanford HAI Blog",               tier:3, cat:"Research",    domain:"hai.stanford.edu"},
  {id:526, name:"Carnegie Mellon News",            tier:3, cat:"Research",    domain:"cmu.edu"},
  {id:527, name:"Oxford Internet Institute",       tier:3, cat:"Research",    domain:"oii.ox.ac.uk"},
  // ── Tier 3: VC Blogs & Analysis ─────────────────────────────────────────────
  {id:530, name:"a16z Blog",                       tier:3, cat:"VC",          domain:"a16z.com"},
  {id:531, name:"Y Combinator Blog",               tier:3, cat:"VC",          domain:"ycombinator.com"},
  {id:532, name:"Sequoia Blog",                    tier:3, cat:"VC",          domain:"sequoiacap.com"},
  {id:533, name:"Bessemer State of the Cloud",     tier:3, cat:"VC",          domain:"bvp.com"},
  {id:534, name:"Redpoint Ventures Blog",          tier:3, cat:"VC",          domain:"redpoint.com"},
  {id:535, name:"GGV Capital Blog",                tier:3, cat:"VC",          domain:"ggvc.com"},
  {id:536, name:"General Catalyst Blog",           tier:3, cat:"VC",          domain:"generalcatalyst.com"},
  {id:537, name:"Battery Ventures Blog",           tier:3, cat:"VC",          domain:"battery.com"},
  {id:538, name:"Greylock Blog",                   tier:3, cat:"VC",          domain:"greylock.com"},
  {id:539, name:"Index Ventures Blog",             tier:3, cat:"VC",          domain:"indexventures.com"},
  {id:540, name:"Accel Blog",                      tier:3, cat:"VC",          domain:"accel.com"},
  {id:541, name:"IVP Blog",                        tier:3, cat:"VC",          domain:"ivp.com"},
  {id:542, name:"Meritech Capital Blog",           tier:3, cat:"VC",          domain:"meritechcapital.com"},
  {id:543, name:"Andreessen Horowitz Essays",      tier:3, cat:"VC",          domain:"a16z.com"},
  {id:544, name:"Turner Novak Newsletter",         tier:3, cat:"VC"},
  {id:545, name:"Invest Like the Best",            tier:3, cat:"VC",          domain:"joincolossus.com"},
  // ── Tier 3: Podcasts — AI & Tech ────────────────────────────────────────────
  {id:550, name:"Dwarkesh Podcast",                tier:3, cat:"Podcasts"},
  {id:551, name:"Acquired Podcast",                tier:3, cat:"Podcasts"},
  {id:552, name:"All-In Podcast",                  tier:3, cat:"Podcasts"},
  {id:553, name:"Lex Fridman Podcast",             tier:3, cat:"Podcasts"},
  {id:554, name:"20VC",                            tier:3, cat:"Podcasts"},
  {id:555, name:"Hard Fork",                       tier:3, cat:"Podcasts"},
  {id:556, name:"Pivot",                           tier:3, cat:"Podcasts"},
  {id:557, name:"Eye on AI",                       tier:3, cat:"Podcasts"},
  {id:558, name:"This Week in Startups",           tier:3, cat:"Podcasts"},
  {id:559, name:"a16z Podcast",                    tier:3, cat:"Podcasts"},
  {id:560, name:"No Priors",                       tier:3, cat:"Podcasts"},
  {id:561, name:"TWIML AI Podcast",                tier:3, cat:"Podcasts"},
  {id:562, name:"Machine Learning Street Talk",    tier:3, cat:"Podcasts"},
  {id:563, name:"Data Skeptic",                    tier:3, cat:"Podcasts"},
  {id:564, name:"Practical AI",                    tier:3, cat:"Podcasts"},
  {id:565, name:"Gradient Descent Podcast",        tier:3, cat:"Podcasts"},
  {id:566, name:"AI in Business Podcast",          tier:3, cat:"Podcasts"},
  {id:567, name:"Superintelligence Podcast",       tier:3, cat:"Podcasts"},
  {id:568, name:"The Cognitive Revolution",        tier:3, cat:"Podcasts"},
  {id:569, name:"Latent Space Podcast",            tier:3, cat:"Podcasts"},
  {id:570, name:"Software Engineering Daily",      tier:3, cat:"Podcasts"},
  {id:571, name:"CoRecursive",                     tier:3, cat:"Podcasts"},
  {id:572, name:"Syntax FM",                       tier:3, cat:"Podcasts"},
  {id:573, name:"Changelog",                       tier:3, cat:"Podcasts"},
  // ── Tier 3: Podcasts — Business & Investing ──────────────────────────────────
  {id:580, name:"My First Million",                tier:3, cat:"Podcasts"},
  {id:581, name:"Masters of Scale",                tier:3, cat:"Podcasts"},
  {id:582, name:"How I Built This",                tier:3, cat:"Podcasts"},
  {id:583, name:"The Knowledge Project",           tier:3, cat:"Podcasts"},
  {id:584, name:"Founders Podcast",                tier:3, cat:"Podcasts"},
  {id:585, name:"Invest Like the Best Podcast",    tier:3, cat:"Podcasts"},
  {id:586, name:"The Full Ratchet",                tier:3, cat:"Podcasts"},
  {id:587, name:"Venture Unlocked",                tier:3, cat:"Podcasts"},
  {id:588, name:"The Pitch",                       tier:3, cat:"Podcasts"},
  {id:589, name:"Grit (Kleiner Perkins)",          tier:3, cat:"Podcasts"},
  {id:590, name:"Bankless Podcast",                tier:3, cat:"Podcasts"},
  {id:591, name:"Tim Ferriss Show",                tier:3, cat:"Podcasts"},
  {id:592, name:"BioTech Nation",                  tier:3, cat:"Podcasts"},
  {id:593, name:"In-Depth (Y Combinator)",         tier:3, cat:"Podcasts"},
  {id:594, name:"Darknet Diaries",                 tier:3, cat:"Podcasts"},
  {id:595, name:"CyberWire Daily",                 tier:3, cat:"Podcasts"},
  {id:596, name:"Security Now",                    tier:3, cat:"Podcasts"},
  {id:597, name:"Lenny's Podcast",                 tier:3, cat:"Podcasts"},
  {id:598, name:"Product Hunt Radio",              tier:3, cat:"Podcasts"},
  {id:599, name:"StartUp Podcast",                 tier:3, cat:"Podcasts"},
];
