// ─── src/data.js — Radical Intelligence Platform constants ──────────────────

export const DATE_RANGES = [
  { id:"7d",  label:"7 days",   days:7   },
  { id:"14d", label:"14 days",  days:14  },
  { id:"30d", label:"30 days",  days:30  },
  { id:"90d", label:"90 days",  days:90  },
  { id:"6m",  label:"6 months", days:183 },
];

export const BLOCKED_DOMAINS = [
  "machinelearningmastery.com","towardsdatascience.com","analyticsvidhya.com",
  "kdnuggets.com","geeksforgeeks.org","freecodecamp.org","hackernoon.com",
  "dev.to","hashnode.com","kaggle.com","paperswithcode.com","arxiv.org",
  "reddit.com","quora.com","stackoverflow.com","stackexchange.com",
  "ycombinator.com","news.ycombinator.com",
  "medium.com","substack.com","ghost.io","wordpress.com","blogspot.com",
  "tumblr.com","weebly.com","wix.com",
  "pypi.org","npmjs.com","github.com","gitlab.com","bitbucket.org",
  "amazon.com","aws.amazon.com","azure.microsoft.com","cloud.google.com",
  "cnblogs.com","habr.com","csdn.net","segmentfault.com","juejin.cn",
  "wwwhatsnew.com","xataka.com",
  "youtube.com","youtu.be","vimeo.com","dailymotion.com",
];

export const BOOLEAN_QUERIES = {
  "Cohere":              `"Cohere" NOT "incoherent" NOT "cohere with"`,
  "Reka":                `("Reka" OR "reka.ai") AND ("AI" OR "LLM" OR "multimodal" OR "startup") NOT "reka dance"`,
  "Writer":              `"Writer" AND ("AI" OR "enterprise" OR "LLM" OR "startup") NOT "screenwriter" NOT "writer's block"`,
  "You.com":             `"You.com" AND ("AI" OR "search" OR "assistant")`,
  "Hebbia":              `"Hebbia" AND ("AI" OR "search" OR "enterprise" OR "knowledge")`,
  "Twelve Labs":         `"Twelve Labs" AND ("AI" OR "video" OR "search" OR "understanding")`,
  "Waabi":               `"Waabi" AND ("AI" OR "autonomous" OR "trucking" OR "self-driving")`,
  "DatologyAI":          `("DatologyAI" OR "Datology AI") AND ("AI" OR "data" OR "curation" OR "LLM")`,
  "V7":                  `"V7" AND ("AI" OR "computer vision" OR "annotation" OR "data") NOT "V7 car" NOT "V7 rocket"`,
  "Delphina":            `"Delphina" AND ("AI" OR "machine learning" OR "AutoML" OR "data") NOT "ship" NOT "hotel"`,
  "Crusoe":              `"Crusoe" AND ("AI" OR "cloud" OR "compute" OR "GPU" OR "infrastructure")`,
  "Unblocked":           `"Unblocked" AND ("AI" OR "developer" OR "engineering" OR "knowledge")`,
  "P-1 AI":              `("P-1 AI" OR "P1 AI") AND ("AI" OR "coding" OR "software agent" OR "developer")`,
  "Ricursive Intelligence": `"Ricursive" AND ("AI" OR "agent" OR "reasoning" OR "intelligence")`,
  "Artificial Agency":   `"Artificial Agency" AND ("AI" OR "gaming" OR "NPC" OR "characters")`,
  "Vizcom":              `"Vizcom" AND ("AI" OR "design" OR "render" OR "sketch")`,
  "Yutori":              `"Yutori" AND ("AI" OR "search" OR "research" OR "agent") NOT "fashion" NOT "clothing"`,
  "Firsthand":           `"Firsthand" AND ("AI" OR "agent" OR "commerce" OR "consumer") NOT "experience" NOT "account"`,
  "Spara":               `"Spara" AND ("AI" OR "sales" OR "revenue" OR "pipeline") NOT "spare"`,
  "Emerald AI":          `("Emerald AI") OR ("Emerald" AND ("workflow automation" OR "business systems" OR "enterprise AI")) NOT "Emerald Isle" NOT "Emerald City" NOT "Emerald Group"`,
  "Mosaic":              `"Mosaic" AND ("AI" OR "finance" OR "FP&A" OR "planning") NOT "tile" NOT "theory" NOT "law"`,
  "Outset":              `"Outset" AND ("AI" OR "research" OR "qualitative" OR "interviews")`,
  "World Labs":          `"World Labs" AND ("AI" OR "spatial" OR "Fei-Fei Li" OR "3D")`,
  "OffDeal":             `"OffDeal" AND ("AI" OR "acquisition" OR "M&A" OR "business")`,
  "Aspect Biosystems":   `"Aspect Biosystems" AND ("bioprinting" OR "tissue" OR "healthcare" OR "biotech")`,
  "Genesis Molecular AI":`("Genesis Therapeutics" OR "Genesis Molecular") AND ("AI" OR "drug discovery" OR "molecular" OR "biotech")`,
  "PocketHealth":        `"PocketHealth" AND ("medical" OR "imaging" OR "radiology" OR "patient")`,
  "Signal 1":            `"Signal 1" AND ("AI" OR "healthcare" OR "hospital" OR "patient") NOT "signal one"`,
  "Ubenwa":              `"Ubenwa" AND ("AI" OR "infant" OR "cry" OR "diagnostics")`,
  "Unlearn":             `"Unlearn" AND ("AI" OR "clinical trial" OR "digital twin" OR "healthcare")`,
  "Intrepid Labs":       `"Intrepid Labs" AND ("AI" OR "biomarker" OR "neurological" OR "healthcare")`,
  "Slingshot AI":        `"Slingshot AI" AND ("AI" OR "medical" OR "scribe" OR "documentation")`,
  "Ribbon":              `"Ribbon Health" AND ("healthcare" OR "navigation" OR "provider" OR "data")`,
  "Attuned Intelligence":`"Attuned" AND ("AI" OR "wellbeing" OR "mental health" OR "emotional")`,
  "Nabla Bio":           `"Nabla Bio" AND ("protein design" OR "protein engineering" OR "nabla.bio" OR "generative biology" OR "de novo protein")`,
  "Chemix":              `"Chemix" AND ("AI" OR "battery" OR "materials" OR "energy")`,
  "ClimateAi":           `"ClimateAi" AND ("AI" OR "climate" OR "agriculture" OR "weather")`,
  "Orbital Materials":   `"Orbital Materials" AND ("AI" OR "materials" OR "discovery")`,
  "Latent Labs":         `"Latent Labs" AND ("AI" OR "protein" OR "biology" OR "generative")`,
  "Periodic Labs":       `"Periodic Labs" AND ("scientific AI" OR "literature synthesis" OR "periodiclabs.ai" OR "hypothesis generation" OR "research AI")`,
  "Muon Space":          `"Muon Space" AND ("satellite" OR "climate" OR "Earth observation")`,
  "Pixxel":              `"Pixxel" AND ("satellite" OR "imaging" OR "Earth" OR "hyperspectral")`,
  "Xanadu":              `"Xanadu" AND ("AI" OR "quantum" OR "computing" OR "photonic")`,
  "Promise Robotics":    `"Promise Robotics" AND ("robotics" OR "construction" OR "automation")`,
  "Synex":               `"Synex" AND ("AI" OR "cell therapy" OR "biotech" OR "manufacturing")`,
  "Serval":              `"Serval" AND ("AI" OR "security" OR "threat" OR "cyber") NOT "animal" NOT "cat"`,
  "Cinder":              `"Cinder" AND ("AI" OR "trust" OR "safety" OR "moderation" OR "cinder.ai") NOT "cinders"`,
  "Decart":              `"Decart" AND ("AI" OR "training" OR "serving" OR "inference" OR "decart.ai")`,
  "Etched":              `"Etched" AND ("AI" OR "ASIC" OR "transformer" OR "silicon" OR "chip" OR "etched.com")`,
};

const RAW_PORTFOLIO = [
  { id:1,  name:"Cohere",           categories:["LLMs","Software"],                  year:2020, description:"Enterprise AI platform for language models — search, summarisation, and generation at scale.", website:"cohere.com",            competitors_seed:["Anthropic","OpenAI","Mistral AI"] },
  { id:2,  name:"Aspect Biosystems",categories:["Biotechnology","Healthcare"],       year:2020, description:"Bioprinting platform for creating living tissues with vascular networks for drug discovery.", website:"aspectbiosystems.com",  competitors_seed:["Organovo","CELLINK","Prellis Biologics"] },
  { id:3,  name:"Genesis Molecular AI",categories:["Biotechnology","Healthcare","Materials"],year:2020,description:"AI-native small molecule drug discovery platform using physics-based molecular simulation.", website:"genesistherapeutics.ai",competitors_seed:["Schrödinger","Recursion Pharmaceuticals","Insilico Medicine"] },
  { id:4,  name:"PocketHealth",     categories:["Healthcare"],                       year:2020, description:"Patient-controlled medical imaging platform — patients own and share their radiology records.", website:"pockethealth.com",     competitors_seed:["Ambra Health","Nanox","Intelerad"] },
  { id:5,  name:"Promise Robotics", categories:["Construction","Robotics","Supply Chain"],year:2020,description:"AI-powered robotic platform for automating off-site construction of building structures.", website:"promiserobotics.com",   competitors_seed:["ICON Build","Mighty Buildings","Skender"] },
  { id:6,  name:"Synex",            categories:["Biotechnology","Healthcare"],       year:2020, description:"Cell therapy manufacturing platform using AI to scale and optimise complex cell production.", website:"synex.bio",             competitors_seed:["Ori Biotech","Multiply Labs","Cellares"] },
  { id:7,  name:"Chemix",           categories:["Climate","Energy","Materials"],     year:2021, description:"AI platform for designing next-generation battery electrolytes and energy storage materials.", website:"chemix.ai",             competitors_seed:["Aionics","Sila Nanotechnologies","QuantumScape"] },
  { id:8,  name:"ClimateAi",        categories:["Climate","Supply Chain"],           year:2021, description:"Climate risk intelligence platform for agriculture and supply chain using hyperlocal AI forecasting.", website:"climate.ai",        competitors_seed:["The Climate Corporation","aWhere","Gro Intelligence"] },
  { id:9,  name:"Waabi",            categories:["Data","Supply Chain","Transportation"],year:2021,description:"AI-first autonomous trucking company using a generative world model to train and deploy self-driving trucks.", website:"waabi.ai",competitors_seed:["Aurora Innovation","TuSimple","Kodiak Robotics"] },
  { id:10, name:"Hebbia",           categories:["Financial Services","LLMs","Search","Software"],year:2022,description:"AI research platform for knowledge work — structured analysis of complex documents at enterprise scale.", website:"hebbia.ai",competitors_seed:["Glean","Perplexity","Kensho"] },
  { id:11, name:"Muon Space",       categories:["Software","Space"],                 year:2022, description:"Full-stack satellite company building a constellation for continuous Earth observation and climate monitoring.", website:"muonspace.com",    competitors_seed:["Planet Labs","Spire Global","HawkEye 360"] },
  { id:12, name:"Pixxel",           categories:["Climate","Software","Space"],       year:2022, description:"Hyperspectral Earth imaging satellite constellation for agriculture, environment and resource monitoring.", website:"pixxel.space",      competitors_seed:["Planet Labs","Satellogic","BlackSky"] },
  { id:13, name:"Signal 1",         categories:["Healthcare"],                       year:2022, description:"AI early warning system for hospitals — predicts patient deterioration before critical events occur.", website:"signal1.ai",          competitors_seed:["Sepsis Alliance","Dascena","BioVitals"] },
  { id:14, name:"Twelve Labs",      categories:["Search","Software"],                year:2022, description:"Video understanding API — multimodal AI that can search, understand and generate insights from video content.", website:"twelvelabs.io",   competitors_seed:["Runway","Google Video AI","Amazon Rekognition"] },
  { id:15, name:"Ubenwa",           categories:["Healthcare"],                       year:2022, description:"AI diagnostics platform that analyses infant cry patterns to detect neurological conditions at birth.", website:"ubenwa.ai",          competitors_seed:["Natus Medical","Masimo","Medtronic Newborn"] },
  { id:16, name:"Unlearn",          categories:["Data","Healthcare"],                year:2022, description:"AI platform that generates digital twin control arms to accelerate and de-risk clinical trials.", website:"unlearn.ai",          competitors_seed:["Medidata Solutions","Inato","Phesi"] },
  { id:17, name:"V7",               categories:["Data","Software"],                  year:2022, description:"AI training data platform for computer vision — annotation, automation and data pipeline management.", website:"v7labs.com",         competitors_seed:["Scale AI","Labelbox","Roboflow"] },
  { id:18, name:"Xanadu",           categories:["Semiconductors"],                   year:2019, description:"Photonic quantum computing company building fault-tolerant quantum computers using light.", website:"xanadu.ai",           competitors_seed:["IonQ","PsiQuantum","IBM Quantum"] },
  { id:19, name:"You.com",          categories:["LLMs","Search"],                    year:2022, description:"AI-powered search engine and productivity assistant with real-time web grounding.", website:"you.com",             competitors_seed:["Perplexity AI","Bing AI","Google AI Overviews"] },
  { id:20, name:"Artificial Agency",categories:["Software"],                         year:2023, description:"AI agent platform for game NPCs — enabling believable, adaptive, LLM-powered non-player characters.", website:"artificialagency.ai",competitors_seed:["Inworld AI","Convai","NVIDIA ACE"] },
  { id:21, name:"DatologyAI",       categories:["Data"],                             year:2023, description:"Automated data curation platform — curates and optimises training datasets to improve LLM quality.", website:"datology.ai",        competitors_seed:["Scale AI","Gretel AI","Snorkel AI"] },
  { id:22, name:"Delphina",         categories:["Data","Software"],                  year:2023, description:"Automated ML pipeline platform — finds the best models and features for tabular data without manual work.", website:"delphina.ai",       competitors_seed:["DataRobot","H2O.ai","Alteryx"] },
  { id:23, name:"Firsthand",        categories:["Software"],                         year:2023, description:"Personal AI that knows your preferences and acts on your behalf for commerce and services.", website:"firsthand.so",       competitors_seed:["Rabbit","Humane","Adept AI"] },
  { id:24, name:"Intrepid Labs",    categories:["Healthcare"],                       year:2023, description:"AI biomarker discovery platform for neurological diseases using multimodal patient data.", website:"intrepidlabs.ai",    competitors_seed:["Praxis Precision Medicine","Tempus","Recursion"] },
  { id:25, name:"Nabla Bio",        categories:["Biotechnology","Materials"],        year:2023, description:"Protein design platform using generative AI to engineer novel proteins for therapeutic and industrial uses.", website:"nabla.bio",          competitors_seed:["Absci","Arzeda","Generate Biomedicines"] },
  { id:26, name:"Orbital Materials",categories:["Climate","Materials"],              year:2023, description:"AI foundation model for materials discovery — accelerating the design of new sustainable materials.", website:"orbitalmaterials.com",competitors_seed:["Citrine Informatics","Kebotix","Enthought"] },
  { id:27, name:"Reka",             categories:["LLMs","Software"],                  year:2023, description:"Multimodal frontier AI company building powerful models for enterprise and consumer applications.", website:"reka.ai",             competitors_seed:["Mistral AI","Cohere","Inflection AI"] },
  { id:28, name:"Emerald AI",       categories:["Software"],                         year:2024, description:"AI platform for enterprise workflow automation with deep integration into existing business systems.", website:"emeraldai.com",      competitors_seed:["UiPath","Automation Anywhere","ServiceNow AI"] },
  { id:29, name:"Latent Labs",      categories:["Biotechnology","Software"],         year:2024, description:"Generative AI for protein structure and function — foundation models for biological sequence design.", website:"latentlabs.ai",     competitors_seed:["EvolutionaryScale","Generate Biomedicines","Profluent"] },
  { id:30, name:"OffDeal",          categories:["Financial Services","Software"],    year:2024, description:"AI platform for SMB M&A — finding, analysing and executing acquisitions for small business buyers.", website:"offdeal.com",        competitors_seed:["Axial","Exitwise","BizBuySell"] },
  { id:31, name:"Spara",            categories:["Software"],                         year:2024, description:"AI-powered revenue intelligence platform for B2B sales teams — pipeline and deal execution.", website:"spara.ai",            competitors_seed:["Gong","Clari","Outreach"] },
  { id:32, name:"World Labs",       categories:["Software"],                         year:2024, description:"Spatial intelligence company building large world models for 3D understanding and generation.", website:"worldlabs.ai",      competitors_seed:["Waymo Research","DeepMind","NVIDIA Research"] },
  { id:33, name:"Writer",           categories:["LLMs","Software"],                  year:2024, description:"Full-stack generative AI for the enterprise — models, platform and applications for business content.", website:"writer.com",          competitors_seed:["Jasper AI","Copy.ai","Anthropic Claude"] },
  { id:34, name:"Attuned Intelligence",categories:["Healthcare"],                    year:2025, description:"AI system for detecting and supporting emotional and cognitive wellbeing in clinical settings.", website:"attuned.ai",          competitors_seed:["Woebot","Limbic","Spring Health"] },
  { id:35, name:"Crusoe",           categories:["Infrastructure"],                   year:2025, description:"Sustainable cloud computing platform using stranded and renewable energy for AI workloads.", website:"crusoe.ai",           competitors_seed:["CoreWeave","Lambda Labs","Voltage Park"] },
  { id:36, name:"Mosaic",           categories:["Financial Services","Software"],    year:2026, description:"AI-native financial planning and analysis platform for modern finance teams.", website:"mosaicapp.com",      competitors_seed:["Pigment","Planful","Anaplan"] },
  { id:37, name:"Outset",           categories:["Software"],                         year:2025, description:"AI-powered qualitative research platform — conducts and analyses user interviews at scale.", website:"outset.ai",           competitors_seed:["UserInterviews","Maze","Respondent"] },
  { id:38, name:"P-1 AI",           categories:["Software"],                         year:2025, description:"AI coding agent that autonomously writes, tests and deploys production software end-to-end.", website:"p1.ai",              competitors_seed:["Devin (Cognition)","GitHub Copilot","Cursor"] },
  { id:39, name:"Periodic Labs",    categories:["Software"],                         year:2025, description:"AI platform for scientific literature synthesis and hypothesis generation in research workflows.", website:"periodiclabs.ai",    competitors_seed:["Elicit","Consensus","Semantic Scholar"] },
  { id:40, name:"Ricursive Intelligence",categories:["Infrastructure","Software"],   year:2025, description:"Recursive AI infrastructure for self-improving agent systems and autonomous reasoning at scale.", website:"ricursive.ai",      competitors_seed:["LangChain","CrewAI","AutoGPT"] },
  { id:41, name:"Ribbon",           categories:["Software"],                         year:2025, description:"AI-powered healthcare navigation platform — helping patients find and access the right care.", website:"ribbon.health",      competitors_seed:["Kyruus","Solv Health","Zocdoc"] },
  { id:42, name:"Serval",           categories:["Software","Security"],              year:2025, description:"AI security platform for autonomous threat detection and response in enterprise environments.", website:"serval.ai",           competitors_seed:["Darktrace","SentinelOne","CrowdStrike"] },
  { id:43, name:"Slingshot AI",     categories:["Healthcare"],                       year:2025, description:"AI-powered clinical documentation platform — automated notes and coding for healthcare providers.", website:"slingshotai.com",    competitors_seed:["Nuance DAX","Abridge","Suki AI"] },
  { id:44, name:"Unblocked",        categories:["Software"],                         year:2025, description:"AI knowledge assistant for engineering teams — surfaces institutional knowledge from codebases and docs.", website:"getunblocked.com",  competitors_seed:["Glean","Notion AI","Guru"] },
  { id:45, name:"Vizcom",           categories:["Software"],                         year:2025, description:"AI design tool for industrial designers — generates photorealistic product renders from sketches.", website:"vizcom.ai",          competitors_seed:["Midjourney","Adobe Firefly","Canva AI"] },
  { id:46, name:"Yutori",           categories:["Search","Software"],                year:2025, description:"AI agent for autonomous web search and deep research — executes complex multi-step research tasks.", website:"yutori.ai",          competitors_seed:["Perplexity","You.com","OpenAI Deep Research"] },
  { id:47, name:"Decart",           categories:["Infrastructure","Software"],        year:2024, description:"AI infrastructure platform for ultra-fast model training and serving, focusing on inference efficiency.", website:"decart.ai",         competitors_seed:["NVIDIA","Groq","Together AI"] },
  { id:48, name:"Etched",           categories:["Semiconductors"],                   year:2024, description:"Semiconductor company building specialized ASICs designed specifically for transformer-based models.", website:"etched.com",         competitors_seed:["NVIDIA","Cerebras","SambaNova"] },
  { id:49, name:"Cinder",           categories:["Software","Security"],              year:2024, description:"Trust and safety platform using AI to manage content moderation and policy enforcement at scale.", website:"cinder.ai",          competitors_seed:["ActiveFence","Unitary","Spectrum Labs"] },
];

export function buildInitialCompanies() {
  return RAW_PORTFOLIO.map(c => ({
    id: c.id,
    name: c.name,
    categories: c.categories,
    year: c.year,
    description: c.description,
    website: c.website,
    enabled: true,
    boolean_query: BOOLEAN_QUERIES[c.name] || `"${c.name}"`,
    boolean_approved: Boolean(BOOLEAN_QUERIES[c.name]),
    competitors: (c.competitors_seed || []).map(name => ({
      id: `comp-${c.id}-${name.replace(/\W+/g, "")}`,
      name,
      rationale: "",
    })),
    runs: [],
    sovRun: null,
  }));
}

export const DEFAULT_OUTLETS = [
  // ── Tier 1: Global News & Business ──────────────────────────────────────────
  {id:1,   name:"The New York Times",           tier:1, cat:"General",  domain:"nytimes.com"},
  {id:2,   name:"The Wall Street Journal",      tier:1, cat:"General",  domain:"wsj.com"},
  {id:3,   name:"Bloomberg",                    tier:1, cat:"General",  domain:"bloomberg.com"},
  {id:4,   name:"Financial Times",              tier:1, cat:"General",  domain:"ft.com"},
  {id:5,   name:"The Economist",                tier:1, cat:"General",  domain:"economist.com"},
  {id:6,   name:"Reuters",                      tier:1, cat:"General",  domain:"reuters.com"},
  {id:7,   name:"BBC News",                     tier:1, cat:"General",  domain:"bbc.com"},
  {id:8,   name:"The Guardian",                 tier:1, cat:"General",  domain:"theguardian.com"},
  {id:9,   name:"CNBC",                         tier:1, cat:"General",  domain:"cnbc.com"},
  {id:10,  name:"Forbes",                       tier:1, cat:"General",  domain:"forbes.com"},
  {id:11,  name:"Fortune",                      tier:1, cat:"General",  domain:"fortune.com"},
  {id:12,  name:"The Atlantic",                 tier:1, cat:"General",  domain:"theatlantic.com"},
  {id:13,  name:"Associated Press",             tier:1, cat:"General",  domain:"apnews.com"},
  {id:14,  name:"The Washington Post",          tier:1, cat:"General",  domain:"washingtonpost.com"},
  {id:15,  name:"Business Insider",             tier:1, cat:"General",  domain:"businessinsider.com"},
  {id:16,  name:"Yahoo Finance",                tier:1, cat:"Finance",  domain:"finance.yahoo.com"},
  {id:17,  name:"MarketWatch",                  tier:1, cat:"Finance",  domain:"marketwatch.com"},
  {id:18,  name:"Barron's",                     tier:1, cat:"Finance",  domain:"barrons.com"},
  {id:19,  name:"South China Morning Post",     tier:1, cat:"General",  domain:"scmp.com"},
  {id:20,  name:"Nikkei Asia",                  tier:1, cat:"General",  domain:"nikkei.com"},
  {id:21,  name:"The Australian Financial Review",tier:1,cat:"Finance", domain:"afr.com"},
  {id:22,  name:"Inc.",                         tier:1, cat:"Startups", domain:"inc.com"},
  // ── Tier 1: Science ─────────────────────────────────────────────────────────
  {id:50,  name:"Nature",                       tier:1, cat:"Science",  domain:"nature.com"},
  {id:51,  name:"Science",                      tier:1, cat:"Science",  domain:"science.org"},
  {id:52,  name:"The Lancet",                   tier:1, cat:"Science",  domain:"thelancet.com"},
  {id:53,  name:"NEJM",                         tier:1, cat:"Science",  domain:"nejm.org"},
  {id:54,  name:"JAMA",                         tier:1, cat:"Science",  domain:"jamanetwork.com"},
  {id:55,  name:"Nature Medicine",              tier:1, cat:"Science",  domain:"nature.com"},
  {id:56,  name:"Nature Biotechnology",         tier:1, cat:"Science",  domain:"nature.com"},
  {id:57,  name:"Nature Machine Intelligence",  tier:1, cat:"AI",       domain:"nature.com"},
  // ── Tier 2: Core Tech ───────────────────────────────────────────────────────
  {id:100, name:"TechCrunch",                   tier:2, cat:"Tech",     domain:"techcrunch.com"},
  {id:101, name:"Wired",                        tier:2, cat:"Tech",     domain:"wired.com"},
  {id:102, name:"MIT Technology Review",        tier:2, cat:"Tech",     domain:"technologyreview.com"},
  {id:103, name:"VentureBeat",                  tier:2, cat:"Tech",     domain:"venturebeat.com"},
  {id:104, name:"The Verge",                    tier:2, cat:"Tech",     domain:"theverge.com"},
  {id:105, name:"Ars Technica",                 tier:2, cat:"Tech",     domain:"arstechnica.com"},
  {id:106, name:"IEEE Spectrum",                tier:2, cat:"Tech",     domain:"spectrum.ieee.org"},
  {id:107, name:"CNET",                         tier:2, cat:"Tech",     domain:"cnet.com"},
  {id:108, name:"ZDNet",                        tier:2, cat:"Tech",     domain:"zdnet.com"},
  {id:109, name:"Axios",                        tier:2, cat:"Tech",     domain:"axios.com"},
  {id:110, name:"GeekWire",                     tier:2, cat:"Tech",     domain:"geekwire.com"},
  {id:111, name:"Fast Company",                 tier:2, cat:"Tech",     domain:"fastcompany.com"},
  {id:112, name:"Sifted",                       tier:2, cat:"Tech",     domain:"sifted.eu"},
  {id:113, name:"Engadget",                     tier:2, cat:"Tech",     domain:"engadget.com"},
  {id:114, name:"The Information",              tier:2, cat:"Tech",     domain:"theinformation.com"},
  // ── Tier 2: VC & Startups ───────────────────────────────────────────────────
  {id:150, name:"PitchBook",                    tier:2, cat:"VC",       domain:"pitchbook.com"},
  {id:151, name:"Crunchbase News",              tier:2, cat:"VC",       domain:"news.crunchbase.com"},
  {id:152, name:"CB Insights",                  tier:2, cat:"VC",       domain:"cbinsights.com"},
  {id:153, name:"Hacker News",                  tier:2, cat:"VC",       domain:"ycombinator.com"},
  // ── Tier 2: AI ──────────────────────────────────────────────────────────────
  {id:200, name:"The Decoder",                  tier:2, cat:"AI"},
  {id:201, name:"The Gradient",                 tier:2, cat:"AI"},
  {id:202, name:"Import AI",                    tier:2, cat:"AI"},
  {id:203, name:"The Rundown AI",               tier:2, cat:"AI"},
  {id:204, name:"AI Business",                  tier:2, cat:"AI"},
  {id:205, name:"MarkTechPost",                 tier:2, cat:"AI"},
  {id:206, name:"Stratechery",                  tier:2, cat:"AI"},
  {id:207, name:"Semianalysis",                 tier:2, cat:"AI"},
  {id:208, name:"Ben's Bites",                  tier:2, cat:"AI"},
  {id:209, name:"AlphaSignal",                  tier:2, cat:"AI"},
  // ── Tier 2: Healthcare & Biotech ────────────────────────────────────────────
  {id:250, name:"STAT News",                    tier:2, cat:"Healthcare",domain:"statnews.com"},
  {id:251, name:"Fierce Biotech",               tier:2, cat:"Healthcare",domain:"fiercebiotech.com"},
  {id:252, name:"Fierce Healthcare",            tier:2, cat:"Healthcare",domain:"fiercehealthcare.com"},
  {id:253, name:"Endpoints News",               tier:2, cat:"Healthcare",domain:"endpts.com"},
  {id:254, name:"BioPharma Dive",               tier:2, cat:"Healthcare",domain:"biopharmadive.com"},
  {id:255, name:"MedCity News",                 tier:2, cat:"Healthcare",domain:"medcitynews.com"},
  {id:256, name:"MobiHealthNews",               tier:2, cat:"Healthcare",domain:"mobihealthnews.com"},
  {id:257, name:"GenomeWeb",                    tier:2, cat:"Healthcare",domain:"genomeweb.com"},
  {id:258, name:"FierceBiotech",                tier:2, cat:"Biotech"},
  {id:259, name:"BioWorld",                     tier:2, cat:"Biotech"},
  {id:260, name:"Labiotech",                    tier:2, cat:"Biotech"},
  {id:261, name:"GEN",                          tier:2, cat:"Biotech"},
  // ── Tier 2: Climate & Energy ────────────────────────────────────────────────
  {id:300, name:"CleanTechnica",                tier:2, cat:"Climate"},
  {id:301, name:"Canary Media",                 tier:2, cat:"Climate",  domain:"canarymedia.com"},
  {id:302, name:"Carbon Brief",                 tier:2, cat:"Climate",  domain:"carbonbrief.org"},
  {id:303, name:"GreenBiz",                     tier:2, cat:"Climate",  domain:"greenbiz.com"},
  {id:304, name:"Bloomberg Green",              tier:2, cat:"Climate"},
  {id:305, name:"E&E News",                     tier:2, cat:"Climate"},
  // ── Tier 2: Semiconductors ──────────────────────────────────────────────────
  {id:350, name:"Semiconductor Engineering",    tier:2, cat:"Semiconductor"},
  {id:351, name:"EE Times",                     tier:2, cat:"Semiconductor"},
  {id:352, name:"The Chip Letter",              tier:2, cat:"Semiconductor"},
  {id:353, name:"AnandTech",                    tier:2, cat:"Semiconductor"},
  // ── Tier 2: Security ────────────────────────────────────────────────────────
  {id:380, name:"Cybersecurity Dive",           tier:2, cat:"Security"},
  {id:381, name:"Dark Reading",                 tier:2, cat:"Security"},
  {id:382, name:"Krebs on Security",            tier:2, cat:"Security"},
  {id:383, name:"Security Week",                tier:2, cat:"Security"},
  // ── Tier 2: Canada ──────────────────────────────────────────────────────────
  {id:400, name:"The Globe and Mail",           tier:2, cat:"Canada",   domain:"theglobeandmail.com"},
  {id:401, name:"The Logic",                    tier:2, cat:"Canada",   domain:"thelogic.co"},
  {id:402, name:"BetaKit",                      tier:2, cat:"Canada",   domain:"betakit.com"},
  {id:403, name:"Financial Post",               tier:2, cat:"Canada",   domain:"financialpost.com"},
  {id:404, name:"CBC News",                     tier:2, cat:"Canada",   domain:"cbc.ca"},
  // ── Tier 2: Science ─────────────────────────────────────────────────────────
  {id:420, name:"Scientific American",          tier:2, cat:"Science"},
  {id:421, name:"Quanta Magazine",              tier:2, cat:"Science"},
  {id:422, name:"New Scientist",                tier:2, cat:"Science"},
  {id:423, name:"ScienceDaily",                 tier:2, cat:"Science"},
  {id:424, name:"Phys.org",                     tier:2, cat:"Science"},
  // ── Tier 2: Space & Robotics ────────────────────────────────────────────────
  {id:440, name:"SpaceNews",                    tier:2, cat:"Space"},
  {id:441, name:"Electrek",                     tier:2, cat:"Transportation"},
  {id:442, name:"Robotics Business Review",     tier:2, cat:"Robotics"},
  {id:443, name:"Construction Dive",            tier:2, cat:"Construction"},
  // ── Tier 3: Podcasts ────────────────────────────────────────────────────────
  {id:500, name:"Dwarkesh Podcast",             tier:3, cat:"Podcasts"},
  {id:501, name:"Acquired Podcast",             tier:3, cat:"Podcasts"},
  {id:502, name:"All-In Podcast",               tier:3, cat:"Podcasts"},
  {id:503, name:"Lex Fridman Podcast",          tier:3, cat:"Podcasts"},
  {id:504, name:"20VC",                         tier:3, cat:"Podcasts"},
  {id:505, name:"Hard Fork",                    tier:3, cat:"Podcasts"},
  {id:506, name:"Pivot",                        tier:3, cat:"Podcasts"},
  {id:507, name:"Eye on AI",                    tier:3, cat:"Podcasts"},
  {id:508, name:"This Week in Startups",        tier:3, cat:"Podcasts"},
  {id:509, name:"a16z Podcast",                 tier:3, cat:"Podcasts"},
  {id:510, name:"BioTech Nation",               tier:3, cat:"Podcasts"},
];
